# Generated by Django 4.0 on 2022-06-07 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerName', models.CharField(max_length=40)),
                ('CropName', models.CharField(max_length=20)),
                ('Price', models.IntegerField(default=0)),
                ('Description', models.TextField(blank=True)),
                ('Quantity', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
