# Generated by Django 4.0 on 2022-06-08 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agroplus', '0004_sell_image_name_alter_sell_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='Image',
            field=models.ImageField(default=datetime.datetime(2022, 6, 8, 19, 32, 55, 113735, tzinfo=utc), upload_to='static/Sell_images'),
        ),
    ]
