# Generated by Django 4.0 on 2022-06-08 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agroplus', '0007_alter_sell_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='Image',
            field=models.ImageField(default=datetime.datetime(2022, 6, 8, 19, 36, 18, 333687, tzinfo=utc), upload_to='static/Sell_images'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='Image_Name_with_extension',
            field=models.CharField(default='image', max_length=20),
        ),
    ]
