# Generated by Django 4.0 on 2022-06-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroplus', '0009_rename_image_name_with_extension_sell_image_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='Image_Name',
        ),
        migrations.AlterField(
            model_name='sell',
            name='Image',
            field=models.ImageField(default='static/Sell_images/AGROPLUS.png', upload_to='static/Sell_images'),
        ),
    ]
