# Generated by Django 4.0 on 2022-06-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroplus', '0010_remove_sell_image_name_alter_sell_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='Price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sell',
            name='Quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
