# Generated by Django 4.0 on 2022-06-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroplus', '0012_alter_sell_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Sell_images/'),
        ),
    ]
