# Generated by Django 4.0.3 on 2022-06-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroplus', '0020_alter_sell_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='imgpath',
            field=models.CharField(default='', max_length=200),
        ),
    ]
