# Generated by Django 4.0 on 2022-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroplus', '0022_alter_sell_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CropName', models.CharField(max_length=20)),
                ('Price', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
